### ISSUE TITLE
Compose intro

### ISSUE THREAD

**Issue by vladyslavmaistruk** [vladyslavmaistruk/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити

**Comment by vladyslavmaistruk** [comment]
I've found required information on this link 
https://github.com/binary-studio-academy/stage-2-how-developers-work/tree/master/donald-trump

**Comment by dasha-korotkykh** [comment]
Will do! Which file should I check for overview?
