### ISSUE TITLE
Compose blocks with extra information

### ISSUE THREAD

**Issue by vladyslavmaistruk** [vladyslavmaistruk/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самій, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issues

**Comment by vladyslavmaistruk** [comment]
I've found required information on this link 
https://github.com/binary-studio-academy/stage-2-how-developers-work/tree/master/donald-trump
